version: "3.8"
services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=best-listens
    ports:
      - "5432:5432"
    container_name: postgresDB_c
    volumes:
      - ./userMicroservice/postgres-db:/var/lib/postgresql

  music-microservice:
    build:
      context: musicMicroservice
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    container_name: musicMicroservice_c
    restart: unless-stopped
    volumes:
      - ./musicMicroservice:/app
    depends_on:
      - postgres

  user-microservice:
    build:
      context: userMicroservice
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: userMicroservice_c
    ports:
      - "3002:3002"
    volumes:
      - ./userMicroservice:/app
    depends_on:
      - postgres

  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    container_name: front-end_c
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - user-microservice
